apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-cm
  namespace: demo
data:
  my.cnf: |
    [client]
    socket=/var/run/mysqld/mysqld.sock
    !includedir /etc/mysql/conf.d/
    !includedir /etc/mysql/mysql.conf.d/                                      
    [mysqld]
    bind-address=0.0.0.0
    port=3306
    server-id=1
    skip-host-cache
    skip-name-resolve
    datadir=/var/lib/mysql
    socket=/var/run/mysqld/mysqld.sock
    secure-file-priv=/var/lib/mysql-files
    user=mysql  
    pid-file=/var/run/mysqld/mysqld.pid
    socket=/var/run/mysqld/mysqld.sock
    basedir=/var/lib/mysql
    datadir=/var/lib/mysql/data
    symbolic-links=0
    skip_name_resolve
    log_bin=mysql-bin
    binlog_format=mixed
    expire_logs_days=30
    init_connect='SET collation_connection = utf8mb4_unicode_ci'
    init_connect='SET NAMES utf8mb4'
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    default-time_zone='+8:00'
    skip-character-set-client-handshake
    max_connections=1000
    max_connect_errors = 6000
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: demo
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      name: server
      targetPort: 3306
      nodePort: 30603
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: demo
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      name: server
      targetPort: 3306
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: demo
  name: mysql
spec:
  serviceName: mysql-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      volumes:
      - name: mysql-config-volume
        configMap:
          name: demo-cm
          items:
           - key: my.cnf
             path: my.cnf
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: Always
        args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        ports:
        - containerPort: 3306
          protocol: TCP
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: '123456'
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-config-volume
          mountPath: /etc/mysql/mysql.conf.d
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
        annotations:
      spec:
        storageClassName: local
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
    - metadata:
        name: mysql-config-volume
        annotations:
      spec:
        storageClassName: local
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  selector:
    matchLabels:
      app: mysql            