server:
  servlet:
    context-path: /
  port: 8092
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2048MB
      max-request-size: 2048MB
  main:
    allow-bean-definition-overriding: true
  application:
    name: dubbo-springboot-demo-provider
management:
  endpoints:
    web:
      exposure:
        include: "*"
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    #address: zookeeper://10.10.10.99:2181
    #timeout: 2500000
      #parameters:
        #blockUntilConnectedWait: 250
    address: nacos://10.10.10.99:30218
    group: dubbo
    namespace: public
    parameters:
      consumer:
        url: true
  config-center:
    #address: zookeeper://10.10.10.99:2181
    address: nacos://10.10.10.99:30218
    group: dubbo
    namespace: public
  metadata-report:
    address: nacos://10.10.10.99:30218
    group: dubbo
    namespace: public
    #address: zookeeper://10.10.10.99:2181
